# Generated by Django 5.2.7 on 2025-10-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_product_image_alter_product_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
    ]
